import { Cormorant_Upright, Open_Sans} from "next/font/google";
import "./globals.css";

const cromorant_upright = Cormorant_Upright({
  subsets: ["latin"], 
  weight:["300", "400", "500", "600", "700"],
  variable: "--font-cormorant-upright",
});

const open_sans = Open_Sans({
  subsets: ["latin"], 
  weight:["300", "400", "500", "600", "700", "800"],
  variable: "--font-open_sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cromorant_upright.variable} ${open_sans} `}
      >
        {children}
      </body>
    </html>
  );
}
